# Generated by Django 4.1.10 on 2023-12-07 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_with_friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_with_friend_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='chat_with_friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_with_friend.chatwithfriend'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagemessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_with_friend.message'),
        ),
        migrations.AddField(
            model_name='chatwithfriend',
            name='message_req_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_with_friend_req_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatwithfriend',
            name='message_req_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_with_friend_req_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
