# Generated by Django 4.1.10 on 2024-10-02 20:27

import base.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='thumbnail')),
                ('name', models.CharField(max_length=56)),
                ('isLive', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, default='', max_length=512)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', related_query_name='live_stream', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestream.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', related_query_name='reaction', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestream.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
    ]
