# Generated by Django 4.1.10 on 2023-12-07 10:49

from django.db import migrations, models
import django.db.models.deletion
import reseller_payment_method.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('accountHolderName', models.CharField(max_length=128)),
                ('accountNumber', models.CharField(max_length=128)),
                ('branchName', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('qrCodeImage', models.ImageField(blank=True, null=True, upload_to='QRCode/')),
                ('network', models.CharField(max_length=56)),
                ('depositAddress', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MobileBanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequestInMobileBanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attactment', models.ImageField(null=True, upload_to=reseller_payment_method.models.upload_to)),
                ('note', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('ammountInDollar', models.CharField(max_length=30, null=True)),
                ('ammountInBGCOIN', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('CANCEL', 'cancel')], default='pending', max_length=20)),
                ('mobileBanking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reseller_payment_method.mobilebanking')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequestInCryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attactment', models.ImageField(null=True, upload_to=reseller_payment_method.models.upload_to)),
                ('note', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('ammountInDollar', models.CharField(max_length=30, null=True)),
                ('ammountInBGCOIN', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('CANCEL', 'cancel')], default='pending', max_length=20)),
                ('cryptoCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reseller_payment_method.cryptocurrency')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequestInBankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attactment', models.ImageField(null=True, upload_to=reseller_payment_method.models.upload_to)),
                ('note', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('ammountInDollar', models.CharField(max_length=30, null=True)),
                ('ammountInBGCOIN', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('CANCEL', 'cancel')], default='pending', max_length=20)),
                ('bankTransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reseller_payment_method.banktransfer')),
            ],
        ),
    ]
