# Generated by Django 4.1.10 on 2024-10-02 20:27

import base.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('win', models.BooleanField(default=False)),
                ('purchaseDate', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LotteryName', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('drawPriceAmount', models.IntegerField()),
                ('numberOfWinner', models.IntegerField()),
                ('lotteryuuid', models.CharField(max_length=255, null=True)),
                ('prizeImage', models.CharField(max_length=255, null=True)),
                ('coverImage', models.CharField(max_length=255, null=True)),
                ('firstPrize', models.CharField(max_length=255, null=True)),
                ('secondPrize', models.CharField(max_length=255, null=True)),
                ('thirdPrize', models.CharField(max_length=255, null=True)),
                ('totalNumberOfTickets', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('firstPrizeName', models.CharField(max_length=56, null=True)),
                ('secondPrizeName', models.CharField(max_length=56, null=True)),
                ('thirdPrizeName', models.CharField(max_length=56, null=True)),
                ('numberOfFirstWinner', models.IntegerField(default=1)),
                ('numberOfSecondWinner', models.IntegerField(default=2)),
                ('numberOfThirdWinner', models.IntegerField(default=3)),
                ('bannerColor', models.CharField(blank=True, max_length=56, null=True)),
                ('ticketSellOpeningTime', models.DateTimeField(auto_now_add=True)),
                ('ticketSellClosingTime', models.DateTimeField(blank=True)),
                ('drawStatus', models.CharField(blank=True, max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('firstPrizeDrawIsComplete', models.BooleanField(default=False)),
                ('secondPrizeDrawIsComplete', models.BooleanField(default=False)),
                ('thirdPrizeDrawIsComplete', models.BooleanField(default=False)),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
        migrations.CreateModel(
            name='TicketWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('luckyNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_draw_app.luckynumber')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_draw_app.ticket')),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
        migrations.CreateModel(
            name='TicketBuyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseDate', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('pickNumber', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket_draw_app.ticket')),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
        migrations.AddField(
            model_name='luckynumber',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_draw_app.ticket'),
        ),
    ]
