# Generated by Django 4.1.10 on 2023-12-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoOn', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('duration', models.CharField(blank=True, max_length=56)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('raised', 'raised'), ('ended', 'ended'), ('inAnotherCall', 'inAnotherCall')], default='pending', max_length=56)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
