# Generated by Django 4.1.10 on 2023-12-07 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calling_app2', '0001_initial'),
        ('chat_with_friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='callee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_from_callees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_from_callers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call',
            name='chat_with_friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', related_query_name='call', to='chat_with_friend.chatwithfriend'),
        ),
    ]
