# Generated by Django 4.1.10 on 2024-10-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_and_achievement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
