# Generated by Django 4.1.10 on 2023-12-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpinningBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchTime', models.DateTimeField(unique=True)),
                ('onGoingBatch', models.BooleanField(default=True)),
                ('winField', models.CharField(max_length=3, null=True)),
                ('winAmount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidType', models.CharField(choices=[('2x', '2x'), ('4x', '4x'), ('6x', '6x')], default='2x', max_length=3)),
                ('amount', models.IntegerField()),
                ('win', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spinning_game.spinningbatch')),
            ],
        ),
    ]
