# Generated by Django 4.1.10 on 2023-12-07 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_call', '0001_initial'),
        ('chat_in_group', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcallmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', related_query_name='group_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupcall',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupcall',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupcalls', related_query_name='groupcall', to='chat_in_group.communitychat'),
        ),
    ]
