# Generated by Django 4.1.10 on 2024-10-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletbankaccounts',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='walletcryptonumbers',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='walletnumbers',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletBankAccounts',
        ),
        migrations.DeleteModel(
            name='WalletCryptoNumbers',
        ),
        migrations.DeleteModel(
            name='WalletNumbers',
        ),
    ]
