# Generated by Django 4.1.10 on 2024-10-02 20:27

import base.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import reseller_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerCoinRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resellerId', models.IntegerField()),
                ('reseller_image_url', models.URLField(blank=True, null=True)),
                ('reseller_name', models.CharField(max_length=255)),
                ('transaction_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bgcoin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('document', models.FileField(upload_to=reseller_app.models.upload_to_reseller)),
                ('doc_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('equalBgCoin', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('transactionId', models.CharField(max_length=50)),
                ('transactionMedium', models.CharField(max_length=50)),
                ('screenshot', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=reseller_app.models.upload_to)),
                ('status', models.CharField(choices=[('denied', 'denied'), ('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('requestFrom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='top_up_request_resellers', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
        migrations.CreateModel(
            name='TopUpRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('denied', 'denied'), ('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('TopUpRequest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reseller_app.topuprequest')),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
        migrations.CreateModel(
            name='ResellerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ResellerCreatedAdminId', to=settings.AUTH_USER_MODEL)),
                ('resellerUserId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ResellerModelID', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
        migrations.CreateModel(
            name='CoinReq',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_req', models.FloatField()),
                ('transaction_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coin_requests', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
    ]
