# Generated by Django 4.1.10 on 2023-12-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
                ('subject', models.CharField(max_length=127)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
