# Generated by Django 4.1.10 on 2024-10-02 20:27

import Lottery.models
import base.base
from django.db import migrations, models
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('LotteryId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('LotteryName', models.CharField(max_length=255)),
                ('Price', models.IntegerField()),
                ('PriceAmount', models.IntegerField()),
                ('NumberOfWinners', models.IntegerField()),
                ('NumberOfTickets', models.IntegerField()),
                ('OpeningTime', models.DateTimeField()),
                ('ClosingTime', models.DateTimeField()),
                ('FirstPrizeName', models.CharField(max_length=255)),
                ('SecondPrizeName', models.CharField(max_length=255)),
                ('ThirdPrizeName', models.CharField(max_length=255)),
                ('TotalFirstPrizeWinner', models.IntegerField()),
                ('TotalSecondPrizeWinner', models.IntegerField()),
                ('TotalThirdPrizeWinner', models.IntegerField()),
                ('isOpen', models.BooleanField(default=True)),
                ('isDrawComplete', models.BooleanField(default=False)),
                ('image_first', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to=Lottery.models.upload_to2)),
                ('image_second', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to=Lottery.models.upload_to3)),
                ('image_third', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to=Lottery.models.upload_to4)),
                ('image_banner', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=Lottery.models.upload_to5)),
                ('image_prizes', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to=Lottery.models.upload_to1)),
                ('type', models.CharField(blank=True, choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=10)),
                ('banner_color', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.IntegerField(blank=True, null=True)),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
        migrations.CreateModel(
            name='LotteryTicket',
            fields=[
                ('userLuckyNumber', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userInput', models.CharField(max_length=6)),
                ('lotteryId', models.UUIDField()),
                ('userId', models.IntegerField()),
                ('purchaseTime', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('winnerId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticketId', models.CharField(max_length=50)),
                ('userId', models.IntegerField()),
                ('prizeType', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('lotteryId', models.UUIDField()),
            ],
            bases=(models.Model, base.base.SerializedModel),
        ),
    ]
