# Generated by Django 4.1.10 on 2024-10-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='ClosingTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='FirstPrizeName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='LotteryName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='NumberOfTickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='NumberOfWinners',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='OpeningTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='PriceAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='SecondPrizeName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='ThirdPrizeName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='TotalFirstPrizeWinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='TotalSecondPrizeWinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='TotalThirdPrizeWinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Special', 'Special'), ('Other', 'Other')], default='Regular', max_length=10),
        ),
    ]
