# Generated by Django 4.1.10 on 2023-12-07 10:49

from django.db import migrations, models
import django_resized.forms
import notifications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=notifications.models.upload_to)),
                ('type', models.CharField(choices=[('type1', 'type1'), ('type2', 'type2'), ('type3', 'type3'), ('type4', 'type4')], default='type1', max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('to_all', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=notifications.models.upload_to)),
                ('type', models.CharField(choices=[('type1', 'type1'), ('type2', 'type2'), ('type3', 'type3'), ('type4', 'type4')], default='type2', max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('to_all', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=notifications.models.upload_to)),
                ('type', models.CharField(choices=[('type1', 'type1'), ('type2', 'type2'), ('type3', 'type3'), ('type4', 'type4')], default='type1', max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('to_all', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('follow_start', 'started following you.'), ('comment', 'comment to your livestream.'), ('mention', 'mentioned you to '), ('follow_back', 'follow you back.'), ('request_for_coins', 'request for')], max_length=20)),
                ('extended_text', models.CharField(default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objectRefId', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
