# Generated by Django 4.1.10 on 2023-12-07 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestnotification',
            name='notification_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_notifications_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestnotification',
            name='notification_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_notifications_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionnotification',
            name='notification_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_notifications_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionnotification',
            name='notification_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_notifications_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamenotification',
            name='notification_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_notifications_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamenotification',
            name='notification_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_notifications_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventnotification',
            name='notification_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventnotification',
            name='notification_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
