name: CI/CD Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to DigitalOcean Droplet using password
        run: |
          sshpass -p ${{ secrets.DROPLET_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
          cd /home/ubuntu/bazigaar-admin/bazigaar-backend  # Navigate to the correct directory
          git pull origin main                             # Pull the latest changes from GitHub
          docker-compose run admin python manage.py collectstatic --noinput  # Collect static files
          docker-compose down                              # Stop the current Docker containers
          docker-compose up --build -d                     # Rebuild and restart Docker containers
          EOF
