name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Debugging: List files after checking out the repo
      - name: List files after checkout
        run: ls -la
        working-directory: ./bazigaar-backend # Assuming it's located here

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m venv myenv
          source myenv/bin/activate  # Linux-style activation
          pip install -r requirements.txt
        working-directory: ./bazigaar-backend

      - name: Run Django tests
        run: |
          source myenv/bin/activate
          python manage.py test
        working-directory: ./root/bazigaar-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh root@188.166.209.196 "
            cd /root/bazigaar-backend &&
            git pull origin main &&
            source myenv/bin/activate &&
            pip install -r requirements.txt &&
            sudo systemctl restart gunicorn &&
            sudo systemctl reload nginx
          "
